[
    {
        "number": 2,
        "created_at": "2024-05-23T09:47:02Z",
        "updated_at": "2024-05-23T09:47:04Z",
        "url": "https://api.github.com/repos/username/evidently/code-scanning/alerts/2",
        "html_url": "https://github.com/username/evidently/security/code-scanning/2",
        "state": "open",
        "fixed_at": null,
        "dismissed_by": null,
        "dismissed_at": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "rule": {
            "id": "py/stack-trace-exposure",
            "severity": "error",
            "description": "Information exposure through an exception",
            "name": "py/stack-trace-exposure",
            "tags": [
                "external/cwe/cwe-209",
                "external/cwe/cwe-497",
                "security"
            ],
            "security_severity_level": "medium"
        },
        "tool": {
            "name": "CodeQL",
            "guid": null,
            "version": "2.17.4"
        },
        "most_recent_instance": {
            "ref": "refs/heads/main",
            "analysis_key": ".github/workflows/codeql.yml:analyze",
            "environment": "{\"build-mode\":\"none\",\"language\":\"python\"}",
            "category": "/language:python",
            "state": "open",
            "commit_sha": "2601cb1b52c8a1395cd3ae0128c86dda6c67dcff",
            "message": {
                "text": "Stack trace information flows to this location and may be exposed to an external user."
            },
            "location": {
                "path": "examples/integrations/fastapi_monitoring/fastapi/app.py",
                "start_line": 65,
                "end_line": 65,
                "start_column": 37,
                "end_column": 58
            },
            "classifications": []
        },
        "instances_url": "https://api.github.com/repos/username/evidently/code-scanning/alerts/2/instances"
    },
    {
        "number": 1,
        "created_at": "2024-05-23T09:47:02Z",
        "updated_at": "2024-05-23T09:47:04Z",
        "url": "https://api.github.com/repos/username/evidently/code-scanning/alerts/1",
        "html_url": "https://github.com/username/evidently/security/code-scanning/1",
        "state": "open",
        "fixed_at": null,
        "dismissed_by": null,
        "dismissed_at": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "rule": {
            "id": "py/flask-debug",
            "severity": "error",
            "description": "Flask app is run in debug mode",
            "name": "py/flask-debug",
            "tags": [
                "external/cwe/cwe-215",
                "external/cwe/cwe-489",
                "security"
            ],
            "security_severity_level": "high"
        },
        "tool": {
            "name": "CodeQL",
            "guid": null,
            "version": "2.17.4"
        },
        "most_recent_instance": {
            "ref": "refs/heads/main",
            "analysis_key": ".github/workflows/codeql.yml:analyze",
            "environment": "{\"build-mode\":\"none\",\"language\":\"python\"}",
            "category": "/language:python",
            "state": "open",
            "commit_sha": "2601cb1b52c8a1395cd3ae0128c86dda6c67dcff",
            "message": {
                "text": "A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger."
            },
            "location": {
                "path": "examples/integrations/grafana_monitoring_service/metrics_app/app.py",
                "start_line": 237,
                "end_line": 237,
                "start_column": 5,
                "end_column": 24
            },
            "classifications": []
        },
        "instances_url": "https://api.github.com/repos/username/evidently/code-scanning/alerts/1/instances"
    }
]