[
    {
        "number": 14,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-06-10T18:31:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/14",
        "html_url": "https://github.com/username/sinabs/security/dependabot/14",
        "created_at": "2024-05-24T01:34:36Z",
        "updated_at": "2024-05-24T01:34:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 13,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Jinja2"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-h75v-3vvj-5mfj",
            "cve_id": "CVE-2024-34064",
            "summary": "Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter",
            "description": "The `xmlattr` filter in affected versions of Jinja accepts keys containing non-attribute characters. XML/HTML attributes cannot contain spaces, `/`, `>`, or `=`, as each would then be interpreted as starting a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. The fix for the previous GHSA-h5c8-rqwp-cp95 CVE-2024-22195 only addressed spaces but not other characters.\n\nAccepting keys as user input is now explicitly considered an unintended use case of the `xmlattr` filter, and code that does so without otherwise validating the input should be flagged as insecure, regardless of Jinja version. Accepting _values_ as user input continues to be safe.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-h75v-3vvj-5mfj",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-34064",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj"
                },
                {
                    "url": "https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-34064"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/567XIGSZMABG6TSMYWD7MIYNJSUQQRUC"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GCLF44KY43BSVMTE6S53B4V5WP3FRRSE"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SSCBHIL6BYKR5NRCBXP4XMP2CEEKGFVS"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZALNWE3TXPPHVPSI3AZ5CTMSTAVN5UMS"
                },
                {
                    "url": "https://github.com/advisories/GHSA-h75v-3vvj-5mfj"
                }
            ],
            "published_at": "2024-05-06T14:20:59Z",
            "updated_at": "2024-06-10T18:30:58Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Jinja2"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.1.4",
                    "first_patched_version": {
                        "identifier": "3.1.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
                "score": 5.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Jinja2"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.1.4",
            "first_patched_version": {
                "identifier": "3.1.4"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/13",
        "html_url": "https://github.com/username/sinabs/security/dependabot/13",
        "created_at": "2024-05-24T01:34:36Z",
        "updated_at": "2024-05-24T01:34:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 12,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "idna"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jjg7-2v4v-x38h",
            "cve_id": "CVE-2024-3651",
            "summary": "Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode",
            "description": "### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-jjg7-2v4v-x38h",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-3651",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jjg7-2v4v-x38h"
                }
            ],
            "published_at": "2024-04-11T21:32:40Z",
            "updated_at": "2024-04-11T21:32:40Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "idna"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.7",
                    "first_patched_version": {
                        "identifier": "3.7"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 6.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "idna"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.7",
            "first_patched_version": {
                "identifier": "3.7"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/12",
        "html_url": "https://github.com/username/sinabs/security/dependabot/12",
        "created_at": "2024-05-24T01:34:36Z",
        "updated_at": "2024-05-24T01:34:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 11,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "jinja2"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-h5c8-rqwp-cp95",
            "cve_id": "CVE-2024-22195",
            "summary": "Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter",
            "description": "The `xmlattr` filter in affected versions of Jinja accepts keys containing spaces. XML/HTML attributes cannot contain spaces, as each would then be interpreted as a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. Note that accepting keys as user input is not common or a particularly intended use case of the `xmlattr` filter, and an application doing so should already be verifying what keys are provided regardless of this fix.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-h5c8-rqwp-cp95",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-22195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/jinja/security/advisories/GHSA-h5c8-rqwp-cp95"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-22195"
                },
                {
                    "url": "https://github.com/pallets/jinja/commit/716795349a41d4983a9a4771f7d883c96ea17be7"
                },
                {
                    "url": "https://github.com/pallets/jinja/releases/tag/3.1.3"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5XCWZD464AJJJUBOO7CMPXQ4ROBC6JX2/"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2024/01/msg00010.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DELCVUUYX75I5K4Q5WMJG4MUZJA6VAIP/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O7YWRBX6JQCWC2XXCTZ55C7DPMGICCN3/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-h5c8-rqwp-cp95"
                }
            ],
            "published_at": "2024-01-11T15:20:48Z",
            "updated_at": "2024-01-27T03:30:20Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jinja2"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.1.3",
                    "first_patched_version": {
                        "identifier": "3.1.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
                "score": 5.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "jinja2"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.1.3",
            "first_patched_version": {
                "identifier": "3.1.3"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/11",
        "html_url": "https://github.com/username/sinabs/security/dependabot/11",
        "created_at": "2024-05-24T01:34:36Z",
        "updated_at": "2024-05-24T01:34:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 10,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-g4mx-q9vg-27p4",
            "cve_id": "CVE-2023-45803",
            "summary": "urllib3's request body not stripped after redirect from 303 status changes request method to GET",
            "description": "urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 303 \"See Other\" after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although the behavior of removing the request body is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers.\n\nFrom [RFC 9110 Section 9.3.1](https://www.rfc-editor.org/rfc/rfc9110.html#name-get):\n\n> A client SHOULD NOT generate content in a GET request unless it is made directly to an origin server that has previously indicated, in or out of band, that such a request has a purpose and will be adequately supported.\n\n## Affected usages\n\nBecause the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable.\n\nBoth of the following conditions must be true to be affected by this vulnerability:\n\n* If you're using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON)\n* The origin service is compromised and starts redirecting using 303 to a malicious peer or the redirected-to service becomes compromised.\n\n## Remediation\n\nYou can remediate this vulnerability with any of the following steps:\n\n* Upgrade to a patched version of urllib3 (v1.26.18 or v2.0.7)\n* Disable redirects for services that you aren't expecting to respond with redirects with `redirects=False`.\n* Disable automatic redirects with `redirects=False` and handle 303 redirects manually by stripping the HTTP request body.\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-g4mx-q9vg-27p4",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-45803",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/4e50fbc5db74e32cabd5ccc1ab81fc103adfe0b3"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/b594c5ceaca38e1ac215f916538fb128e3526a36"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/releases/tag/1.26.18"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/releases/tag/2.0.7"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-45803"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9"
                },
                {
                    "url": "https://www.rfc-editor.org/rfc/rfc9110.html#name-get"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-212.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-g4mx-q9vg-27p4"
                }
            ],
            "published_at": "2023-10-17T20:15:25Z",
            "updated_at": "2023-11-06T16:24:46Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.0.0, < 2.0.7",
                    "first_patched_version": {
                        "identifier": "2.0.7"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 0, < 1.26.18",
                    "first_patched_version": {
                        "identifier": "1.26.18"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                "score": 4.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 0, < 1.26.18",
            "first_patched_version": {
                "identifier": "1.26.18"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/10",
        "html_url": "https://github.com/username/sinabs/security/dependabot/10",
        "created_at": "2024-05-24T01:34:36Z",
        "updated_at": "2024-05-24T01:34:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 9,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-v845-jxx5-vc9f",
            "cve_id": "CVE-2023-43804",
            "summary": "`Cookie` HTTP header isn't stripped on cross-origin redirects",
            "description": "urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly.\n\nUsers **must** handle redirects themselves instead of relying on urllib3's automatic redirects to achieve safe processing of the `Cookie` header, thus we decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Using an affected version of urllib3 (patched in v1.26.17 and v2.0.6)\n* Using the `Cookie` header on requests, which is mostly typical for impersonating a browser.\n* Not disabling HTTP redirects\n* Either not using HTTPS or for the origin server to redirect to a malicious origin.\n\n## Remediation\n\n* Upgrading to at least urllib3 v1.26.17 or v2.0.6\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Cookie` header.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-v845-jxx5-vc9f",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-43804",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-43804"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-192.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-v845-jxx5-vc9f"
                }
            ],
            "published_at": "2023-10-02T23:27:05Z",
            "updated_at": "2023-11-04T00:30:22Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.0.0, < 2.0.6",
                    "first_patched_version": {
                        "identifier": "2.0.6"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.26.17",
                    "first_patched_version": {
                        "identifier": "1.26.17"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N",
                "score": 5.9
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 1.26.17",
            "first_patched_version": {
                "identifier": "1.26.17"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/9",
        "html_url": "https://github.com/username/sinabs/security/dependabot/9",
        "created_at": "2024-05-24T01:34:36Z",
        "updated_at": "2024-05-24T01:34:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 8,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-xqr8-7jwr-rhp7",
            "cve_id": "CVE-2023-37920",
            "summary": "Removal of e-Tugra root certificate",
            "description": "Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\n e-Tugra's root certificates are being removed pursuant to an investigation prompted by reporting of security issues in their systems. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A).",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-xqr8-7jwr-rhp7",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-37920",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7"
                },
                {
                    "url": "https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-37920"
                },
                {
                    "url": "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/certifi/PYSEC-2023-135.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-xqr8-7jwr-rhp7"
                }
            ],
            "published_at": "2023-07-25T14:43:53Z",
            "updated_at": "2023-11-09T05:05:47Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "certifi"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2015.4.28, < 2023.7.22",
                    "first_patched_version": {
                        "identifier": "2023.7.22"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-345",
                    "name": "Insufficient Verification of Data Authenticity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 2015.4.28, < 2023.7.22",
            "first_patched_version": {
                "identifier": "2023.7.22"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/8",
        "html_url": "https://github.com/username/sinabs/security/dependabot/8",
        "created_at": "2024-05-24T01:34:36Z",
        "updated_at": "2024-05-24T01:34:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 7,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pygments"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-mrwq-x4v8-fh7p",
            "cve_id": "CVE-2022-40896",
            "summary": "Pygments vulnerable to ReDoS",
            "description": "A ReDoS issue was discovered in `pygments/lexers/smithy.py` in Pygments until 2.15.0 via SmithyLexer.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-mrwq-x4v8-fh7p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-40896",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-40896"
                },
                {
                    "url": "https://github.com/pygments/pygments/blob/master/pygments/lexers/smithy.py#L61"
                },
                {
                    "url": "https://github.com/pygments/pygments/commit/97eb3d5ec7c1b3ea4fcf9dee30a2309cf92bd194"
                },
                {
                    "url": "https://github.com/pygments/pygments/commit/dd52102c38ebe78cd57748e09f38929fd283ad04"
                },
                {
                    "url": "https://github.com/pygments/pygments/commit/fdf182a7af85b1deeeb637ca970d31935e7c9d52"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pygments/PYSEC-2023-117.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/EZGMXALE3HSP4OXC7UUWIKX3OXKZDTY3"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VUZO4BQCIY2S2KZYHERQMKURB7AHXDBO"
                },
                {
                    "url": "https://pypi.org/project/Pygments"
                },
                {
                    "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages-part-2"
                },
                {
                    "url": "https://github.com/advisories/GHSA-mrwq-x4v8-fh7p"
                }
            ],
            "published_at": "2023-07-19T15:30:26Z",
            "updated_at": "2024-03-28T13:28:18Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pygments"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.15.0",
                    "first_patched_version": {
                        "identifier": "2.15.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
                "score": 5.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-434",
                    "name": "Unrestricted Upload of File with Dangerous Type"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pygments"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.15.0",
            "first_patched_version": {
                "identifier": "2.15.0"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/7",
        "html_url": "https://github.com/username/sinabs/security/dependabot/7",
        "created_at": "2024-05-24T01:34:36Z",
        "updated_at": "2024-05-24T01:34:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 6,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-j8r2-6x86-q33q",
            "cve_id": "CVE-2023-32681",
            "summary": "Unintended leak of Proxy-Authorization header in requests",
            "description": "### Impact\n\nSince Requests v2.3.0, Requests has been vulnerable to potentially leaking `Proxy-Authorization` headers to destination servers, specifically during redirects to an HTTPS origin. This is a product of how `rebuild_proxies` is used to recompute and [reattach the `Proxy-Authorization` header](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/sessions.py#L319-L328) to requests when redirected. Note this behavior has _only_ been observed to affect proxied requests when credentials are supplied in the URL user information component (e.g. `https://username:password@proxy:8080`).\n\n**Current vulnerable behavior(s):**\n\n1. HTTP → HTTPS: **leak**\n2. HTTPS → HTTP: **no leak**\n3. HTTPS → HTTPS: **leak**\n4. HTTP → HTTP: **no leak**\n\nFor HTTP connections sent through the proxy, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into further tunneled requests. This results in Requests forwarding the header to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate those credentials.\n\nThe reason this currently works for HTTPS connections in Requests is the `Proxy-Authorization` header is also handled by urllib3 with our usage of the ProxyManager in adapters.py with [`proxy_manager_for`](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/adapters.py#L199-L235). This will compute the required proxy headers in `proxy_headers` and pass them to the Proxy Manager, avoiding attaching them directly to the Request object. This will be our preferred option going forward for default usage.\n\n### Patches\nStarting in Requests v2.31.0, Requests will no longer attach this header to redirects with an HTTPS destination. This should have no negative impacts on the default behavior of the library as the proxy credentials are already properly being handled by urllib3's ProxyManager.\n\nFor users with custom adapters, this _may_ be potentially breaking if you were already working around this behavior. The previous functionality of `rebuild_proxies` doesn't make sense in any case, so we would encourage any users impacted to migrate any handling of Proxy-Authorization directly into their custom adapter.\n\n### Workarounds\nFor users who are not able to update Requests immediately, there is one potential workaround.\n\nYou may disable redirects by setting `allow_redirects` to `False` on all calls through Requests top-level APIs. Note that if you're currently relying on redirect behaviors, you will need to capture the 3xx response codes and ensure a new request is made to the redirect destination.\n```\nimport requests\nr = requests.get('http://github.com/', allow_redirects=False)\n```\n\n### Credits\n\nThis vulnerability was discovered and disclosed by the following individuals.\n\nDennis Brinkrolf, Haxolot (https://haxolot.com/)\nTobias Funke, (tobiasfunke93@gmail.com)",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-j8r2-6x86-q33q",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-32681",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q"
                },
                {
                    "url": "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-32681"
                },
                {
                    "url": "https://github.com/psf/requests/releases/tag/v2.31.0"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2023-74.yaml"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202309-08"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ"
                },
                {
                    "url": "https://github.com/advisories/GHSA-j8r2-6x86-q33q"
                }
            ],
            "published_at": "2023-05-22T20:36:32Z",
            "updated_at": "2024-03-27T20:09:55Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.3.0, < 2.31.0",
                    "first_patched_version": {
                        "identifier": "2.31.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
                "score": 6.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 2.3.0, < 2.31.0",
            "first_patched_version": {
                "identifier": "2.31.0"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/6",
        "html_url": "https://github.com/username/sinabs/security/dependabot/6",
        "created_at": "2024-05-24T01:34:35Z",
        "updated_at": "2024-05-24T01:34:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 5,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-43fp-rhv2-5gv8",
            "cve_id": "CVE-2022-23491",
            "summary": "Certifi removing TrustCor root certificate",
            "description": "Certifi 2022.12.07 removes root certificates from \"TrustCor\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\nTrustCor's root certificates are being removed pursuant to an investigation prompted by media reporting that TrustCor's ownership also operated a business that produced spyware. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ).",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-43fp-rhv2-5gv8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-23491",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8"
                },
                {
                    "url": "https://github.com/certifi/python-certifi/commit/9e9e840925d7b8e76c76fdac1fab7e6e88c1c3b8"
                },
                {
                    "url": "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-23491"
                },
                {
                    "url": "https://github.com/advisories/GHSA-43fp-rhv2-5gv8"
                }
            ],
            "published_at": "2022-12-07T23:05:18Z",
            "updated_at": "2023-01-29T05:05:37Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "certifi"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2017.11.05, < 2022.12.07",
                    "first_patched_version": {
                        "identifier": "2022.12.07"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:H/A:N",
                "score": 6.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-345",
                    "name": "Insufficient Verification of Data Authenticity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 2017.11.05, < 2022.12.07",
            "first_patched_version": {
                "identifier": "2022.12.07"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/5",
        "html_url": "https://github.com/username/sinabs/security/dependabot/5",
        "created_at": "2024-05-24T01:34:35Z",
        "updated_at": "2024-05-24T01:34:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 4,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "torch"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-47fc-vmwq-366v",
            "cve_id": "CVE-2022-45907",
            "summary": "PyTorch vulnerable to arbitrary code execution",
            "description": "In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely. The fix for this issue is available in version 1.13.1. There is a release checker in [issue #89855](https://github.com/pytorch/pytorch/issues/89855).",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-47fc-vmwq-366v",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-45907",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-45907"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/88868"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/commit/767f6aa49fe20a2766b9843d01e3b7f7793df6a3"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/89855"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/pull/89189"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/releases/tag/v1.13.1"
                },
                {
                    "url": "https://github.com/advisories/GHSA-47fc-vmwq-366v"
                }
            ],
            "published_at": "2022-11-26T03:30:27Z",
            "updated_at": "2023-01-30T05:01:22Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "torch"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "<= 1.13.0",
                    "first_patched_version": {
                        "identifier": "1.13.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-77",
                    "name": "Improper Neutralization of Special Elements used in a Command ('Command Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "torch"
            },
            "severity": "critical",
            "vulnerable_version_range": "<= 1.13.0",
            "first_patched_version": {
                "identifier": "1.13.1"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/4",
        "html_url": "https://github.com/username/sinabs/security/dependabot/4",
        "created_at": "2024-05-24T01:34:35Z",
        "updated_at": "2024-05-24T01:34:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 3,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "py"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "development"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-w596-4wvx-j9j6",
            "cve_id": "CVE-2022-42969",
            "summary": "ReDoS in py library when used with subversion ",
            "description": "The py library through 1.11.0 for Python allows remote attackers to conduct a ReDoS (Regular expression Denial of Service) attack via a Subversion repository with crafted info data, because the InfoSvnCommand argument is mishandled.\n\nThe particular codepath in question is the regular expression at `py._path.svnurl.InfoSvnCommand.lspattern` and is only relevant when dealing with subversion (svn) projects. Notably the codepath is not used in the popular pytest project. The developers of the pytest package have released version `7.2.0` which removes their dependency on `py`. Users of `pytest` seeing alerts relating to this advisory may update to version `7.2.0` of `pytest` to resolve this issue. See https://github.com/pytest-dev/py/issues/287#issuecomment-1290407715 for additional context.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-w596-4wvx-j9j6",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-42969",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-42969"
                },
                {
                    "url": "https://github.com/pytest-dev/py/issues/287"
                },
                {
                    "url": "https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316"
                },
                {
                    "url": "https://github.com/pytest-dev/py/issues/288"
                },
                {
                    "url": "https://github.com/pytest-dev/pytest/issues/10392"
                },
                {
                    "url": "https://news.ycombinator.com/item?id=34163710"
                },
                {
                    "url": "https://pypi.org/project/py"
                },
                {
                    "url": "https://github.com/advisories/GHSA-w596-4wvx-j9j6"
                }
            ],
            "published_at": "2022-10-16T12:00:23Z",
            "updated_at": "2023-08-17T05:01:50Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "py"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 1.11.0",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-1333",
                    "name": "Inefficient Regular Expression Complexity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "py"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 1.11.0",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/3",
        "html_url": "https://github.com/username/sinabs/security/dependabot/3",
        "created_at": "2024-05-24T01:34:35Z",
        "updated_at": "2024-05-24T01:34:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 2,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-fpfv-jqm9-f5jm",
            "cve_id": "CVE-2021-34141",
            "summary": "Incorrect Comparison in NumPy",
            "description": "Incomplete string comparison in the numpy.core component in NumPy1.9.x, which allows attackers to fail the APIs via constructing specific string objects.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-fpfv-jqm9-f5jm",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-34141",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-34141"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18993"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18993#issuecomment-1010735102"
                },
                {
                    "url": "https://github.com/advisories/GHSA-fpfv-jqm9-f5jm"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-855.yaml"
                }
            ],
            "published_at": "2021-12-18T00:00:41Z",
            "updated_at": "2023-01-27T05:07:10Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.22",
                    "first_patched_version": {
                        "identifier": "1.22"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-697",
                    "name": "Incorrect Comparison"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 1.22",
            "first_patched_version": {
                "identifier": "1.22"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/2",
        "html_url": "https://github.com/username/sinabs/security/dependabot/2",
        "created_at": "2024-05-24T01:34:35Z",
        "updated_at": "2024-05-24T01:34:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 1,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "Pipfile.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-6p56-wp2h-9hxr",
            "cve_id": "CVE-2021-33430",
            "summary": "NumPy Buffer Overflow (Disputed)",
            "description": "A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service.\n\nNOTE: The vendor does not agree this is a vulnerability; In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-6p56-wp2h-9hxr",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-33430",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-33430"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18939"
                },
                {
                    "url": "https://github.com/numpy/numpy/commit/ae317fd9ff3e79c0eac357d723bfc29cbd625f2e"
                },
                {
                    "url": "https://github.com/advisories/GHSA-6p56-wp2h-9hxr"
                }
            ],
            "published_at": "2022-01-07T00:09:39Z",
            "updated_at": "2024-01-11T21:28:19Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 1.9.0, < 1.21",
                    "first_patched_version": {
                        "identifier": "1.21"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 1.9.0, < 1.21",
            "first_patched_version": {
                "identifier": "1.21"
            }
        },
        "url": "https://api.github.com/repos/username/sinabs/dependabot/alerts/1",
        "html_url": "https://github.com/username/sinabs/security/dependabot/1",
        "created_at": "2024-05-24T01:34:35Z",
        "updated_at": "2024-05-24T01:34:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]