[
    {
        "number": 4,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "poetry.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-05-20T22:07:29Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/username/cltk/dependabot/alerts/4",
        "html_url": "https://github.com/username/cltk/security/dependabot/4",
        "created_at": "2024-05-22T23:29:14Z",
        "updated_at": "2024-05-22T23:29:14Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 3,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "black"
            },
            "manifest_path": "poetry.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-fj7x-q9j7-g6q6",
            "cve_id": "CVE-2024-21503",
            "summary": "Black vulnerable to Regular Expression Denial of Service (ReDoS)",
            "description": "Versions of the package black before 24.3.0 are vulnerable to Regular Expression Denial of Service (ReDoS) via the lines_with_leading_tabs_expanded function in the strings.py file. An attacker could exploit this vulnerability by crafting a malicious input that causes a denial of service.\n\nExploiting this vulnerability is possible when running Black on untrusted input, or if you habitually put thousands of leading tab characters in your docstrings.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-fj7x-q9j7-g6q6",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-21503",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-21503"
                },
                {
                    "url": "https://github.com/psf/black/commit/f00093672628d212b8965a8993cee8bedf5fe9b8"
                },
                {
                    "url": "https://github.com/psf/black/releases/tag/24.3.0"
                },
                {
                    "url": "https://security.snyk.io/vuln/SNYK-PYTHON-BLACK-6256273"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/black/PYSEC-2024-48.yaml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-fj7x-q9j7-g6q6"
                }
            ],
            "published_at": "2024-03-19T06:30:52Z",
            "updated_at": "2024-03-20T15:24:02Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "black"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 0, < 24.3.0",
                    "first_patched_version": {
                        "identifier": "24.3.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-1333",
                    "name": "Inefficient Regular Expression Complexity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "black"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 0, < 24.3.0",
            "first_patched_version": {
                "identifier": "24.3.0"
            }
        },
        "url": "https://api.github.com/repos/username/cltk/dependabot/alerts/3",
        "html_url": "https://github.com/username/cltk/security/dependabot/3",
        "created_at": "2024-05-22T23:29:13Z",
        "updated_at": "2024-05-22T23:29:13Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 2,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "py"
            },
            "manifest_path": "poetry.lock",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-w596-4wvx-j9j6",
            "cve_id": "CVE-2022-42969",
            "summary": "ReDoS in py library when used with subversion ",
            "description": "The py library through 1.11.0 for Python allows remote attackers to conduct a ReDoS (Regular expression Denial of Service) attack via a Subversion repository with crafted info data, because the InfoSvnCommand argument is mishandled.\n\nThe particular codepath in question is the regular expression at `py._path.svnurl.InfoSvnCommand.lspattern` and is only relevant when dealing with subversion (svn) projects. Notably the codepath is not used in the popular pytest project. The developers of the pytest package have released version `7.2.0` which removes their dependency on `py`. Users of `pytest` seeing alerts relating to this advisory may update to version `7.2.0` of `pytest` to resolve this issue. See https://github.com/pytest-dev/py/issues/287#issuecomment-1290407715 for additional context.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-w596-4wvx-j9j6",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-42969",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-42969"
                },
                {
                    "url": "https://github.com/pytest-dev/py/issues/287"
                },
                {
                    "url": "https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316"
                },
                {
                    "url": "https://github.com/pytest-dev/py/issues/288"
                },
                {
                    "url": "https://github.com/pytest-dev/pytest/issues/10392"
                },
                {
                    "url": "https://news.ycombinator.com/item?id=34163710"
                },
                {
                    "url": "https://pypi.org/project/py"
                },
                {
                    "url": "https://github.com/advisories/GHSA-w596-4wvx-j9j6"
                }
            ],
            "published_at": "2022-10-16T12:00:23Z",
            "updated_at": "2023-08-17T05:01:50Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "py"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 1.11.0",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-1333",
                    "name": "Inefficient Regular Expression Complexity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "py"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 1.11.0",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/username/cltk/dependabot/alerts/2",
        "html_url": "https://github.com/username/cltk/security/dependabot/2",
        "created_at": "2024-05-22T23:29:13Z",
        "updated_at": "2024-05-22T23:29:13Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 1,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "PyYAML"
            },
            "manifest_path": "docs/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-8q59-q68h-6hv4",
            "cve_id": "CVE-2020-14343",
            "summary": "Improper Input Validation in PyYAML",
            "description": "A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-8q59-q68h-6hv4",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-14343",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-14343"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc"
                },
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1860466"
                },
                {
                    "url": "https://pypi.org/project/PyYAML/"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpuapr2022.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/SeldonIO/seldon-core/issues/2252"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/issues/420"
                },
                {
                    "url": "https://github.com/advisories/GHSA-8q59-q68h-6hv4"
                }
            ],
            "published_at": "2021-03-25T21:26:26Z",
            "updated_at": "2023-08-23T23:02:02Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "PyYAML"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 5.4",
                    "first_patched_version": {
                        "identifier": "5.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-20",
                    "name": "Improper Input Validation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "PyYAML"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 5.4",
            "first_patched_version": {
                "identifier": "5.4"
            }
        },
        "url": "https://api.github.com/repos/username/cltk/dependabot/alerts/1",
        "html_url": "https://github.com/username/cltk/security/dependabot/1",
        "created_at": "2024-05-22T23:29:13Z",
        "updated_at": "2024-05-22T23:29:13Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]