[
    {
        "number": 40,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pymysql"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-v9hf-5j83-6xpp",
            "cve_id": "CVE-2024-36039",
            "summary": "PyMySQL SQL Injection vulnerability",
            "description": "PyMySQL through 1.1.0 allows SQL injection if used with untrusted JSON input because keys are not escaped by `escape_dict`.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-v9hf-5j83-6xpp",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-36039",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-36039"
                },
                {
                    "url": "https://github.com/PyMySQL/PyMySQL/releases/tag/v1.1.1"
                },
                {
                    "url": "https://github.com/PyMySQL/PyMySQL/commit/521e40050cb386a499f68f483fefd144c493053c"
                },
                {
                    "url": "https://github.com/advisories/GHSA-v9hf-5j83-6xpp"
                }
            ],
            "published_at": "2024-05-21T18:31:23Z",
            "updated_at": "2024-05-21T19:23:16Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pymysql"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 1.1.1",
                    "first_patched_version": {
                        "identifier": "1.1.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-89",
                    "name": "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pymysql"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 1.1.1",
            "first_patched_version": {
                "identifier": "1.1.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/40",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/40",
        "created_at": "2024-05-21T19:27:39Z",
        "updated_at": "2024-05-21T19:27:39Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 39,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pymongo"
            },
            "manifest_path": "etc/requirements_mongo.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-cr6f-gf5w-vhrc",
            "cve_id": "CVE-2024-21506",
            "summary": "PyMongo Out-of-bounds Read in the bson module",
            "description": "Versions of the package pymongo before 4.6.3 are vulnerable to Out-of-bounds Read in the bson module. Using the crafted payload the attacker could force the parser to deserialize unmanaged memory. The parser tries to interpret bytes next to buffer and throws an exception with string. If the following bytes are not printable UTF-8 the parser throws an exception with a single byte.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-cr6f-gf5w-vhrc",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-21506",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-21506"
                },
                {
                    "url": "https://github.com/mongodb/mongo-python-driver/commit/56b6b6dbc267d365d97c037082369dabf37405d2"
                },
                {
                    "url": "https://gist.github.com/keltecc/62a7c2bf74a997d0a7b48a0ff3853a03"
                },
                {
                    "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYMONGO-6370597"
                },
                {
                    "url": "https://github.com/advisories/GHSA-cr6f-gf5w-vhrc"
                }
            ],
            "published_at": "2024-04-06T06:31:08Z",
            "updated_at": "2024-04-08T15:40:18Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pymongo"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 4.6.3",
                    "first_patched_version": {
                        "identifier": "4.6.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:L",
                "score": 5.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pymongo"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 4.6.3",
            "first_patched_version": {
                "identifier": "4.6.3"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/39",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/39",
        "created_at": "2024-05-20T13:27:14Z",
        "updated_at": "2024-05-20T13:27:14Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 38,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-2g68-c3qc-8985",
            "cve_id": "CVE-2024-34069",
            "summary": "Werkzeug debugger vulnerable to remote execution when interacting with attacker controlled domain",
            "description": "The debugger in affected versions of Werkzeug can allow an attacker to execute code on a developer's machine under some circumstances. This requires the attacker to get the developer to interact with a domain and subdomain they control, and enter the debugger PIN, but if they are successful it allows access to the debugger even if it is only running on localhost. This also requires the attacker to guess a URL in the developer's application that will trigger the debugger.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-2g68-c3qc-8985",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-34069",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-34069"
                },
                {
                    "url": "https://github.com/advisories/GHSA-2g68-c3qc-8985"
                }
            ],
            "published_at": "2024-05-06T14:21:27Z",
            "updated_at": "2024-05-06T16:17:35Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Werkzeug"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.0.3",
                    "first_patched_version": {
                        "identifier": "3.0.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-352",
                    "name": "Cross-Site Request Forgery (CSRF)"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "severity": "high",
            "vulnerable_version_range": "< 3.0.3",
            "first_patched_version": {
                "identifier": "3.0.3"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/38",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/38",
        "created_at": "2024-05-20T13:27:14Z",
        "updated_at": "2024-05-20T13:27:14Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 37,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Jinja2"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-h75v-3vvj-5mfj",
            "cve_id": "CVE-2024-34064",
            "summary": "Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter",
            "description": "The `xmlattr` filter in affected versions of Jinja accepts keys containing non-attribute characters. XML/HTML attributes cannot contain spaces, `/`, `>`, or `=`, as each would then be interpreted as starting a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. The fix for the previous GHSA-h5c8-rqwp-cp95 CVE-2024-22195 only addressed spaces but not other characters.\n\nAccepting keys as user input is now explicitly considered an unintended use case of the `xmlattr` filter, and code that does so without otherwise validating the input should be flagged as insecure, regardless of Jinja version. Accepting _values_ as user input continues to be safe.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-h75v-3vvj-5mfj",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-34064",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj"
                },
                {
                    "url": "https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-34064"
                },
                {
                    "url": "https://github.com/advisories/GHSA-h75v-3vvj-5mfj"
                }
            ],
            "published_at": "2024-05-06T14:20:59Z",
            "updated_at": "2024-05-06T16:17:32Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Jinja2"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.1.4",
                    "first_patched_version": {
                        "identifier": "3.1.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
                "score": 5.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Jinja2"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.1.4",
            "first_patched_version": {
                "identifier": "3.1.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/37",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/37",
        "created_at": "2024-05-20T13:27:14Z",
        "updated_at": "2024-05-20T13:27:14Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 36,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "flask-cors"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-84pr-m4jr-85g5",
            "cve_id": "CVE-2024-1681",
            "summary": "flask-cors vulnerable to log injection when the log level is set to debug",
            "description": "corydolphin/flask-cors is vulnerable to log injection when the log level is set to debug. An attacker can inject fake log entries into the log file by sending a specially crafted GET request containing a CRLF sequence in the request path. This vulnerability allows attackers to corrupt log files, potentially covering tracks of other attacks, confusing log post-processing tools, and forging log entries. The issue is due to improper output neutralization for logs.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-84pr-m4jr-85g5",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-1681",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-1681"
                },
                {
                    "url": "https://huntr.com/bounties/25a7a0ba-9fa2-4777-acb6-03e5539bb644"
                },
                {
                    "url": "https://github.com/corydolphin/flask-cors/blob/40acc8092332dfed4bb54d7a4f89a6d479466de7/flask_cors/extension.py#L194"
                },
                {
                    "url": "https://github.com/advisories/GHSA-84pr-m4jr-85g5"
                }
            ],
            "published_at": "2024-04-19T21:31:08Z",
            "updated_at": "2024-05-07T13:28:05Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "flask-cors"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.0.0",
                    "first_patched_version": {
                        "identifier": "4.0.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-117",
                    "name": "Improper Output Neutralization for Logs"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "flask-cors"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 4.0.0",
            "first_patched_version": {
                "identifier": "4.0.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/36",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/36",
        "created_at": "2024-05-20T13:27:14Z",
        "updated_at": "2024-05-20T13:27:14Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 35,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pymongo"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-cr6f-gf5w-vhrc",
            "cve_id": "CVE-2024-21506",
            "summary": "PyMongo Out-of-bounds Read in the bson module",
            "description": "Versions of the package pymongo before 4.6.3 are vulnerable to Out-of-bounds Read in the bson module. Using the crafted payload the attacker could force the parser to deserialize unmanaged memory. The parser tries to interpret bytes next to buffer and throws an exception with string. If the following bytes are not printable UTF-8 the parser throws an exception with a single byte.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-cr6f-gf5w-vhrc",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-21506",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-21506"
                },
                {
                    "url": "https://github.com/mongodb/mongo-python-driver/commit/56b6b6dbc267d365d97c037082369dabf37405d2"
                },
                {
                    "url": "https://gist.github.com/keltecc/62a7c2bf74a997d0a7b48a0ff3853a03"
                },
                {
                    "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYMONGO-6370597"
                },
                {
                    "url": "https://github.com/advisories/GHSA-cr6f-gf5w-vhrc"
                }
            ],
            "published_at": "2024-04-06T06:31:08Z",
            "updated_at": "2024-04-08T15:40:18Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pymongo"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 4.6.3",
                    "first_patched_version": {
                        "identifier": "4.6.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:L",
                "score": 5.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pymongo"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 4.6.3",
            "first_patched_version": {
                "identifier": "4.6.3"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/35",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/35",
        "created_at": "2024-05-20T13:27:13Z",
        "updated_at": "2024-05-20T13:27:13Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 34,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "jinja2"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-h5c8-rqwp-cp95",
            "cve_id": "CVE-2024-22195",
            "summary": "Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter",
            "description": "The `xmlattr` filter in affected versions of Jinja accepts keys containing spaces. XML/HTML attributes cannot contain spaces, as each would then be interpreted as a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. Note that accepting keys as user input is not common or a particularly intended use case of the `xmlattr` filter, and an application doing so should already be verifying what keys are provided regardless of this fix.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-h5c8-rqwp-cp95",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-22195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/jinja/security/advisories/GHSA-h5c8-rqwp-cp95"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-22195"
                },
                {
                    "url": "https://github.com/pallets/jinja/commit/716795349a41d4983a9a4771f7d883c96ea17be7"
                },
                {
                    "url": "https://github.com/pallets/jinja/releases/tag/3.1.3"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5XCWZD464AJJJUBOO7CMPXQ4ROBC6JX2/"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2024/01/msg00010.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DELCVUUYX75I5K4Q5WMJG4MUZJA6VAIP/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O7YWRBX6JQCWC2XXCTZ55C7DPMGICCN3/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-h5c8-rqwp-cp95"
                }
            ],
            "published_at": "2024-01-11T15:20:48Z",
            "updated_at": "2024-01-27T03:30:20Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jinja2"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.1.3",
                    "first_patched_version": {
                        "identifier": "3.1.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
                "score": 5.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "jinja2"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.1.3",
            "first_patched_version": {
                "identifier": "3.1.3"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/34",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/34",
        "created_at": "2024-05-20T13:27:13Z",
        "updated_at": "2024-05-20T13:27:13Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 33,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-hrfv-mqp8-q5rw",
            "cve_id": "CVE-2023-46136",
            "summary": "Werkzeug DoS: High resource usage when parsing multipart/form-data containing a large part with CR/LF character at the beginning",
            "description": "Werkzeug multipart data parser needs to find a boundary that may be between consecutive chunks. That's why parsing is based on looking for newline characters. Unfortunately, code looking for partial boundary in the buffer is written inefficiently, so if we upload a file that starts with CR or LF and then is followed by megabytes of data without these characters: all of these bytes are appended chunk by chunk into internal bytearray and lookup for boundary is performed on growing buffer.\n\nThis allows an attacker to cause a denial of service by sending crafted multipart data to an endpoint that will parse it. The amount of CPU time required can block worker processes from handling legitimate requests. The amount of RAM required can trigger an out of memory kill of the process. If many concurrent requests are sent continuously, this can exhaust or kill all available workers.\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-hrfv-mqp8-q5rw",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-46136",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-hrfv-mqp8-q5rw"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/b1916c0c083e0be1c9d887ee2f3d696922bfc5c1"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-46136"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/f3c803b3ade485a45f12b6d6617595350c0f03e2"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/werkzeug/PYSEC-2023-221.yaml"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/f2300208d5e2a5076cbbb4c2aad71096fd040ef9"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20231124-0008/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-hrfv-mqp8-q5rw"
                }
            ],
            "published_at": "2023-10-25T14:22:59Z",
            "updated_at": "2023-12-03T05:04:51Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "werkzeug"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 3.0.0, < 3.0.1",
                    "first_patched_version": {
                        "identifier": "3.0.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "werkzeug"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.3.8",
                    "first_patched_version": {
                        "identifier": "2.3.8"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 5.7
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                },
                {
                    "cwe_id": "CWE-787",
                    "name": "Out-of-bounds Write"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.3.8",
            "first_patched_version": {
                "identifier": "2.3.8"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/33",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/33",
        "created_at": "2024-05-20T13:27:13Z",
        "updated_at": "2024-05-20T13:27:13Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 32,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "flask"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5wv5-4vpf-pj6m",
            "cve_id": "CVE-2019-1010083",
            "summary": "Pallets Project Flask is vulnerable to Denial of Service via Unexpected memory usage",
            "description": "The Pallets Project Flask before 1.0 is affected by unexpected memory usage. The impact is denial of service. The attack vector is crafted encoded JSON data. The fixed version is 1. NOTE this may overlap CVE-2018-1000656.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-5wv5-4vpf-pj6m",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-1010083",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-1010083"
                },
                {
                    "url": "https://www.palletsprojects.com/blog/flask-1-0-released/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5wv5-4vpf-pj6m"
                }
            ],
            "published_at": "2019-07-19T16:12:46Z",
            "updated_at": "2023-08-14T21:11:53Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "flask"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.0",
                    "first_patched_version": {
                        "identifier": "1.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "flask"
            },
            "severity": "high",
            "vulnerable_version_range": "< 1.0",
            "first_patched_version": {
                "identifier": "1.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/32",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/32",
        "created_at": "2024-05-20T13:27:13Z",
        "updated_at": "2024-05-20T13:27:13Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 31,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9fq2-x9r6-wfmf",
            "cve_id": "CVE-2019-6446",
            "summary": "Numpy Deserialization of Untrusted Data",
            "description": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-9fq2-x9r6-wfmf",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-6446",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-6446"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/12759"
                },
                {
                    "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
                },
                {
                    "url": "https://github.com/numpy/numpy/pull/12889"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:3704"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4"
                },
                {
                    "url": "https://web.archive.org/web/20210124234613/https://www.securityfocus.com/bid/106670"
                },
                {
                    "url": "http://www.securityfocus.com/bid/106670"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9fq2-x9r6-wfmf"
                }
            ],
            "published_at": "2022-05-24T22:00:57Z",
            "updated_at": "2024-04-22T21:20:59Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "<= 1.16.0",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "critical",
            "vulnerable_version_range": "<= 1.16.0",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/31",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/31",
        "created_at": "2024-05-20T13:27:13Z",
        "updated_at": "2024-05-20T13:27:13Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 30,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "flask"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-m2qf-hxjv-5gpq",
            "cve_id": "CVE-2023-30861",
            "summary": "Flask vulnerable to possible disclosure of permanent session cookie due to missing Vary: Cookie header",
            "description": "When all of the following conditions are met, a response containing data intended for one client may be cached and subsequently sent by a proxy to other clients. If the proxy also caches `Set-Cookie` headers, it may send one client's `session` cookie to other clients. The severity depends on the application's use of the session, and the proxy's behavior regarding cookies. The risk depends on _all_ these conditions being met.\n\n1. The application must be hosted behind a caching proxy that does not strip cookies or ignore responses with cookies.\n2. The application sets [`session.permanent = True`](https://flask.palletsprojects.com/en/2.3.x/api/#flask.session.permanent).\n2. The application does not access or modify the session at any point during a request.\n4. [`SESSION_REFRESH_EACH_REQUEST`](https://flask.palletsprojects.com/en/2.3.x/config/#SESSION_REFRESH_EACH_REQUEST) is enabled (the default).\n5. The application does not set a `Cache-Control` header to indicate that a page is private or should not be cached.\n\nThis happens because vulnerable versions of Flask only set the `Vary: Cookie` header when the session is accessed or modified, not when it is refreshed (re-sent to update the expiration) without being accessed or modified.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-m2qf-hxjv-5gpq",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-30861",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/flask/security/advisories/GHSA-m2qf-hxjv-5gpq"
                },
                {
                    "url": "https://github.com/pallets/flask/commit/70f906c51ce49c485f1d355703e9cc3386b1cc2b"
                },
                {
                    "url": "https://github.com/pallets/flask/releases/tag/2.3.2"
                },
                {
                    "url": "https://github.com/pallets/flask/commit/afd63b16170b7c047f5758eb910c416511e9c965"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-30861"
                },
                {
                    "url": "https://github.com/pallets/flask/releases/tag/2.2.5"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/flask/PYSEC-2023-62.yaml"
                },
                {
                    "url": "https://www.debian.org/security/2023/dsa-5442"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20230818-0006/"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/08/msg00024.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-m2qf-hxjv-5gpq"
                }
            ],
            "published_at": "2023-05-01T19:22:20Z",
            "updated_at": "2023-11-06T05:03:38Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "flask"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.3.0, < 2.3.2",
                    "first_patched_version": {
                        "identifier": "2.3.2"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "flask"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.2.5",
                    "first_patched_version": {
                        "identifier": "2.2.5"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-539",
                    "name": "Use of Persistent Cookies Containing Sensitive Information"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "flask"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.2.5",
            "first_patched_version": {
                "identifier": "2.2.5"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/30",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/30",
        "created_at": "2024-05-20T13:27:13Z",
        "updated_at": "2024-05-20T13:27:13Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 29,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-px8h-6qxv-m22q",
            "cve_id": "CVE-2023-23934",
            "summary": "Incorrect parsing of nameless cookies leads to __Host- cookies bypass",
            "description": "Browsers may allow \"nameless\" cookies that look like `=value` instead of `key=value`. A vulnerable browser may allow a compromised application on an adjacent subdomain to exploit this to set a cookie like `=__Host-test=bad` for another subdomain.\n\nWerkzeug <= 2.2.2 will parse the cookie `=__Host-test=bad` as `__Host-test=bad`. If a Werkzeug application is running next to a vulnerable or malicious subdomain which sets such a cookie using a vulnerable browser, the Werkzeug application will see the bad cookie value but the valid cookie key.",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-px8h-6qxv-m22q",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-23934",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-px8h-6qxv-m22q"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-23934"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/cf275f42acad1b5950c50ffe8ef58fe62cdce028"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/releases/tag/2.2.3"
                },
                {
                    "url": "https://www.debian.org/security/2023/dsa-5470"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20230818-0003/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-px8h-6qxv-m22q"
                }
            ],
            "published_at": "2023-02-15T15:37:03Z",
            "updated_at": "2023-09-04T05:06:48Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Werkzeug"
                    },
                    "severity": "low",
                    "vulnerable_version_range": "< 2.2.3",
                    "first_patched_version": {
                        "identifier": "2.2.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:A/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N",
                "score": 2.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-20",
                    "name": "Improper Input Validation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "severity": "low",
            "vulnerable_version_range": "< 2.2.3",
            "first_patched_version": {
                "identifier": "2.2.3"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/29",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/29",
        "created_at": "2024-05-20T13:27:13Z",
        "updated_at": "2024-05-20T13:27:13Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 28,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-xg9f-g7g7-2323",
            "cve_id": "CVE-2023-25577",
            "summary": "High resource usage when parsing multipart form data with many fields",
            "description": "Werkzeug's multipart form data parser will parse an unlimited number of parts, including file parts. Parts can be a small amount of bytes, but each requires CPU time to parse and may use more memory as Python data. If a request can be made to an endpoint that accesses `request.data`, `request.form`, `request.files`, or `request.get_data(parse_form_data=False)`, it can cause unexpectedly high resource usage.\n\nThis allows an attacker to cause a denial of service by sending crafted multipart data to an endpoint that will parse it. The amount of CPU time required can block worker processes from handling legitimate requests. The amount of RAM required can trigger an out of memory kill of the process. Unlimited file parts can use up memory and file handles. If many concurrent requests are sent continuously, this can exhaust or kill all available workers.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-xg9f-g7g7-2323",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25577",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-xg9f-g7g7-2323"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25577"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/517cac5a804e8c4dc4ed038bb20dacd038e7a9f1"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/releases/tag/2.2.3"
                },
                {
                    "url": "https://www.debian.org/security/2023/dsa-5470"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20230818-0003/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-xg9f-g7g7-2323"
                }
            ],
            "published_at": "2023-02-15T15:36:26Z",
            "updated_at": "2023-08-18T15:47:26Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Werkzeug"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.2.3",
                    "first_patched_version": {
                        "identifier": "2.2.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                },
                {
                    "cwe_id": "CWE-770",
                    "name": "Allocation of Resources Without Limits or Throttling"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.2.3",
            "first_patched_version": {
                "identifier": "2.2.3"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/28",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/28",
        "created_at": "2024-05-20T13:27:13Z",
        "updated_at": "2024-05-20T13:27:13Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 27,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-j544-7q9p-6xp8",
            "cve_id": "CVE-2019-14322",
            "summary": "Pallets Werkzeug vulnerable to Path Traversal",
            "description": "In Pallets Werkzeug before 0.15.5, SharedDataMiddleware mishandles drive names (such as C:) in Windows pathnames.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-j544-7q9p-6xp8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-14322",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14322"
                },
                {
                    "url": "https://palletsprojects.com/blog/werkzeug-0-15-5-released/"
                },
                {
                    "url": "http://packetstormsecurity.com/files/163398/Pallets-Werkzeug-0.15.4-Path-Traversal.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-j544-7q9p-6xp8"
                }
            ],
            "published_at": "2022-05-24T16:51:33Z",
            "updated_at": "2023-02-02T01:32:53Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "werkzeug"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 0.15.5",
                    "first_patched_version": {
                        "identifier": "0.15.5"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "severity": "high",
            "vulnerable_version_range": "< 0.15.5",
            "first_patched_version": {
                "identifier": "0.15.5"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/27",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/27",
        "created_at": "2024-05-20T13:27:13Z",
        "updated_at": "2024-05-20T13:27:13Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 26,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "future"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-v3c5-jqr6-7qm8",
            "cve_id": "CVE-2022-40899",
            "summary": "Python Charmers Future denial of service vulnerability",
            "description": "An issue discovered in Python Charmers Future 0.18.2 and earlier allows remote attackers to cause a denial of service via crafted Set-Cookie header from malicious web server. This issue has been patched in version 0.18.3.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-v3c5-jqr6-7qm8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-40899",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-40899"
                },
                {
                    "url": "https://github.com/python/cpython/pull/17157"
                },
                {
                    "url": "https://github.com/PythonCharmers/python-future/blob/master/src/future/backports/http/cookiejar.py#L215"
                },
                {
                    "url": "https://pypi.org/project/future/"
                },
                {
                    "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"
                },
                {
                    "url": "https://github.com/PythonCharmers/python-future/commit/c91d70b34ef0402aef3e9d04364ba98509dca76f"
                },
                {
                    "url": "https://github.com/PythonCharmers/python-future/pull/610"
                },
                {
                    "url": "https://github.com/advisories/GHSA-v3c5-jqr6-7qm8"
                }
            ],
            "published_at": "2022-12-23T00:30:23Z",
            "updated_at": "2023-01-28T05:06:22Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "future"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 0.18.2",
                    "first_patched_version": {
                        "identifier": "0.18.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "future"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 0.18.2",
            "first_patched_version": {
                "identifier": "0.18.3"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/26",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/26",
        "created_at": "2024-05-20T13:27:12Z",
        "updated_at": "2024-05-20T13:27:12Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 25,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-fpfv-jqm9-f5jm",
            "cve_id": "CVE-2021-34141",
            "summary": "Incorrect Comparison in NumPy",
            "description": "Incomplete string comparison in the numpy.core component in NumPy1.9.x, which allows attackers to fail the APIs via constructing specific string objects.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-fpfv-jqm9-f5jm",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-34141",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-34141"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18993"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18993#issuecomment-1010735102"
                },
                {
                    "url": "https://github.com/advisories/GHSA-fpfv-jqm9-f5jm"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-855.yaml"
                }
            ],
            "published_at": "2021-12-18T00:00:41Z",
            "updated_at": "2023-01-27T05:07:10Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.22",
                    "first_patched_version": {
                        "identifier": "1.22"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-697",
                    "name": "Incorrect Comparison"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 1.22",
            "first_patched_version": {
                "identifier": "1.22"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/25",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/25",
        "created_at": "2024-05-20T13:27:12Z",
        "updated_at": "2024-05-20T13:27:12Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 24,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5545-2q6w-2gh6",
            "cve_id": "CVE-2021-41495",
            "summary": "NumPy NULL Pointer Dereference",
            "description": "Null Pointer Dereference vulnerability exists in numpy.sort in NumPy &lt and 1.19 in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-5545-2q6w-2gh6",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-41495",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41495"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/19038"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5545-2q6w-2gh6"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-856.yaml"
                }
            ],
            "published_at": "2022-02-08T00:00:56Z",
            "updated_at": "2023-01-29T05:01:55Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 1.18.5",
                    "first_patched_version": {
                        "identifier": "1.19"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 1.18.5",
            "first_patched_version": {
                "identifier": "1.19"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/24",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/24",
        "created_at": "2024-05-20T13:27:12Z",
        "updated_at": "2024-05-20T13:27:12Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 23,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-f7c7-j99h-c22f",
            "cve_id": "CVE-2021-41496",
            "summary": "Buffer Copy without Checking Size of Input in NumPy",
            "description": "Buffer overflow in the array_from_pyobj function of fortranobject.c in NumPy < 1.19, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-f7c7-j99h-c22f",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-41496",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41496"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/19000"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-f7c7-j99h-c22f"
                }
            ],
            "published_at": "2022-02-08T00:00:56Z",
            "updated_at": "2023-01-27T05:02:20Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 1.18.5",
                    "first_patched_version": {
                        "identifier": "1.19"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 5.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 1.18.5",
            "first_patched_version": {
                "identifier": "1.19"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/23",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/23",
        "created_at": "2024-05-20T13:27:12Z",
        "updated_at": "2024-05-20T13:27:12Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 22,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-frgw-fgh6-9g52",
            "cve_id": "CVE-2017-12852",
            "summary": "Numpy missing input validation",
            "description": "The numpy.pad function in Numpy 1.13.1 and older versions is missing input validation. An empty list or ndarray will stick into an infinite loop, which can allow attackers to cause a DoS attack.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-frgw-fgh6-9g52",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2017-12852",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-12852"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/9560#issuecomment-322395292"
                },
                {
                    "url": "https://github.com/BT123/testcasesForMyRequest/tree/master/CVE-2017-12852"
                },
                {
                    "url": "https://github.com/numpy/numpy/releases/tag/v1.13.3"
                },
                {
                    "url": "https://github.com/advisories/GHSA-frgw-fgh6-9g52"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2017-1.yaml"
                }
            ],
            "published_at": "2022-05-13T01:42:46Z",
            "updated_at": "2023-01-27T05:07:54Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.13.3",
                    "first_patched_version": {
                        "identifier": "1.13.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-835",
                    "name": "Loop with Unreachable Exit Condition ('Infinite Loop')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "high",
            "vulnerable_version_range": "< 1.13.3",
            "first_patched_version": {
                "identifier": "1.13.3"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/22",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/22",
        "created_at": "2024-05-20T13:27:12Z",
        "updated_at": "2024-05-20T13:27:12Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 21,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-6p56-wp2h-9hxr",
            "cve_id": "CVE-2021-33430",
            "summary": "NumPy Buffer Overflow (Disputed)",
            "description": "A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service.\n\nNOTE: The vendor does not agree this is a vulnerability; In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-6p56-wp2h-9hxr",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-33430",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-33430"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18939"
                },
                {
                    "url": "https://github.com/numpy/numpy/commit/ae317fd9ff3e79c0eac357d723bfc29cbd625f2e"
                },
                {
                    "url": "https://github.com/advisories/GHSA-6p56-wp2h-9hxr"
                }
            ],
            "published_at": "2022-01-07T00:09:39Z",
            "updated_at": "2024-01-11T21:28:19Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 1.9.0, < 1.21",
                    "first_patched_version": {
                        "identifier": "1.21"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 1.9.0, < 1.21",
            "first_patched_version": {
                "identifier": "1.21"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/21",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/21",
        "created_at": "2024-05-20T13:27:12Z",
        "updated_at": "2024-05-20T13:27:12Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 20,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pyyaml"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-rprw-h62v-c2w7",
            "cve_id": "CVE-2017-18342",
            "summary": "PyYAML insecurely deserializes YAML strings leading to arbitrary code execution",
            "description": "In PyYAML before 4.1, the `yaml.load()` API could execute arbitrary code. In other words, `yaml.safe_load` is not used.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-rprw-h62v-c2w7",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2017-18342",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-18342"
                },
                {
                    "url": "https://github.com/marshmallow-code/apispec/issues/278"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/issues/193"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/pull/74"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/blob/master/CHANGES"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JEX7IPV5P2QJITAMA5Z63GQCZA5I6NVZ/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KSQQMRUQSXBSUXLCRD3TSZYQ7SEZRKCE/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M6JCFGEIEOFMWWIXGHSELMKQDD4CV2BA/"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202003-45"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/commit/7b68405c81db889f83c32846462b238ccae5be80"
                },
                {
                    "url": "https://github.com/advisories/GHSA-rprw-h62v-c2w7"
                }
            ],
            "published_at": "2019-01-04T17:45:26Z",
            "updated_at": "2023-09-05T17:58:47Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pyyaml"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 4.1",
                    "first_patched_version": {
                        "identifier": "4.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pyyaml"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 4.1",
            "first_patched_version": {
                "identifier": "4.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/20",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/20",
        "created_at": "2024-05-20T13:27:12Z",
        "updated_at": "2024-05-20T13:27:12Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 19,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-Cors"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-xc3p-ff3m-f46v",
            "cve_id": "CVE-2020-25032",
            "summary": "Flask-Cors Directory Traversal vulnerability",
            "description": "An issue was discovered in Flask-CORS (aka CORS Middleware for Flask) before 3.0.9. It allows `../` directory traversal to access private resources because resource matching does not ensure that pathnames are in a canonical format.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-xc3p-ff3m-f46v",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-25032",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-25032"
                },
                {
                    "url": "https://github.com/corydolphin/flask-cors/commit/67c4b2cc98ae87cf1fa7df4f97fd81b40c79b895"
                },
                {
                    "url": "https://github.com/corydolphin/flask-cors/releases/tag/3.0.9"
                },
                {
                    "url": "https://www.debian.org/security/2020/dsa-4775"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00028.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00032.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00039.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00048.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-xc3p-ff3m-f46v"
                }
            ],
            "published_at": "2021-05-06T18:51:48Z",
            "updated_at": "2023-08-31T16:42:28Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Flask-Cors"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.0.9",
                    "first_patched_version": {
                        "identifier": "3.0.9"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-Cors"
            },
            "severity": "high",
            "vulnerable_version_range": "< 3.0.9",
            "first_patched_version": {
                "identifier": "3.0.9"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/19",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/19",
        "created_at": "2024-05-20T13:27:12Z",
        "updated_at": "2024-05-20T13:27:12Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 18,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pyyaml"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-6757-jp84-gxfx",
            "cve_id": "CVE-2020-1747",
            "summary": "Improper Input Validation in PyYAML",
            "description": "A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-6757-jp84-gxfx",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-1747",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-1747"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/pull/386"
                },
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2/"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0"
                },
                {
                    "url": "https://github.com/advisories/GHSA-6757-jp84-gxfx"
                }
            ],
            "published_at": "2021-04-20T16:14:24Z",
            "updated_at": "2023-08-25T00:08:24Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pyyaml"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 5.3.1",
                    "first_patched_version": {
                        "identifier": "5.3.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-20",
                    "name": "Improper Input Validation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pyyaml"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 5.3.1",
            "first_patched_version": {
                "identifier": "5.3.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/18",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/18",
        "created_at": "2024-05-20T13:27:12Z",
        "updated_at": "2024-05-20T13:27:12Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 17,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "PyYAML"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-8q59-q68h-6hv4",
            "cve_id": "CVE-2020-14343",
            "summary": "Improper Input Validation in PyYAML",
            "description": "A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-8q59-q68h-6hv4",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-14343",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-14343"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc"
                },
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1860466"
                },
                {
                    "url": "https://pypi.org/project/PyYAML/"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpuapr2022.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/SeldonIO/seldon-core/issues/2252"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/issues/420"
                },
                {
                    "url": "https://github.com/advisories/GHSA-8q59-q68h-6hv4"
                }
            ],
            "published_at": "2021-03-25T21:26:26Z",
            "updated_at": "2023-08-23T23:02:02Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "PyYAML"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 5.4",
                    "first_patched_version": {
                        "identifier": "5.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-20",
                    "name": "Improper Input Validation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "PyYAML"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 5.4",
            "first_patched_version": {
                "identifier": "5.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/17",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/17",
        "created_at": "2024-05-20T13:27:11Z",
        "updated_at": "2024-05-20T13:27:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 16,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "jinja2"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-g3rq-g295-4j3m",
            "cve_id": "CVE-2020-28493",
            "summary": "Regular Expression Denial of Service (ReDoS) in Jinja2",
            "description": "This affects the package jinja2 from 0.0.0 and before 2.11.3. The ReDOS vulnerability of the regex is mainly due to the sub-pattern [a-zA-Z0-9._-]+.[a-zA-Z0-9._-]+ This issue can be mitigated by Markdown to format user content instead of the urlize filter, or by implementing request timeouts and limiting process memory.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-g3rq-g295-4j3m",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-28493",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-28493"
                },
                {
                    "url": "https://github.com/pallets/jinja/pull/1343"
                },
                {
                    "url": "https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py%23L20"
                },
                {
                    "url": "https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PVAKCOO7VBVUBM3Q6CBBTPBFNP5NDXF4/"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202107-19"
                },
                {
                    "url": "https://github.com/pallets/jinja/commit/15ef8f09b659f9100610583938005a7a10472d4d"
                },
                {
                    "url": "https://github.com/advisories/GHSA-g3rq-g295-4j3m"
                }
            ],
            "published_at": "2021-03-19T21:28:05Z",
            "updated_at": "2023-09-07T19:35:25Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jinja2"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.11.3",
                    "first_patched_version": {
                        "identifier": "2.11.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "jinja2"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.11.3",
            "first_patched_version": {
                "identifier": "2.11.3"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/16",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/16",
        "created_at": "2024-05-20T13:27:11Z",
        "updated_at": "2024-05-20T13:27:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 15,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "psutil"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-qfc5-mcwq-26q8",
            "cve_id": "CVE-2019-18874",
            "summary": "Double Free in psutil",
            "description": "psutil (aka python-psutil) through 5.6.5 can have a double free. This occurs because of refcount mishandling within a while or for loop that converts system data into a Python object.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-qfc5-mcwq-26q8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-18874",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-18874"
                },
                {
                    "url": "https://github.com/giampaolo/psutil/pull/1616"
                },
                {
                    "url": "https://github.com/giampaolo/psutil/commit/7d512c8e4442a896d56505be3e78f1156f443465"
                },
                {
                    "url": "https://github.com/giampaolo/psutil/blob/master/HISTORY.rst#566"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2019/11/msg00018.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2P7QI7MOTZTFXQYU23CP3RAWXCERMOAS/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OLETTJYZL2SMBUI4Q2NGBMGPDPP54SRG/"
                },
                {
                    "url": "https://usn.ubuntu.com/4204-1/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-qfc5-mcwq-26q8"
                }
            ],
            "published_at": "2020-03-12T17:02:50Z",
            "updated_at": "2023-01-09T05:02:21Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "psutil"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 5.6.5",
                    "first_patched_version": {
                        "identifier": "5.6.6"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-415",
                    "name": "Double Free"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "psutil"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 5.6.5",
            "first_patched_version": {
                "identifier": "5.6.6"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/15",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/15",
        "created_at": "2024-05-20T13:27:11Z",
        "updated_at": "2024-05-20T13:27:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 14,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-gq9m-qvpx-68hc",
            "cve_id": "CVE-2019-14806",
            "summary": "Pallets Werkzeug Insufficient Entropy",
            "description": "Pallets Werkzeug before 0.15.3, when used with Docker, has insufficient debugger PIN randomness because Docker containers share the same machine id.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-gq9m-qvpx-68hc",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-14806",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14806"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/blob/7fef41b120327d3912fbe12fb64f1951496fcf3e/src/werkzeug/debug/__init__.py#L168"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/00bc43b1672e662e5e3b8cecd79e67fc968fa246"
                },
                {
                    "url": "https://palletsprojects.com/blog/werkzeug-0-15-3-released/"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00034.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00047.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-gq9m-qvpx-68hc"
                }
            ],
            "published_at": "2019-08-21T16:15:24Z",
            "updated_at": "2023-08-31T09:34:58Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "werkzeug"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 0.15.3",
                    "first_patched_version": {
                        "identifier": "0.15.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-331",
                    "name": "Insufficient Entropy"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "severity": "high",
            "vulnerable_version_range": "< 0.15.3",
            "first_patched_version": {
                "identifier": "0.15.3"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/14",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/14",
        "created_at": "2024-05-20T13:27:11Z",
        "updated_at": "2024-05-20T13:27:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 13,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "SQLAlchemy"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-887w-45rq-vxgf",
            "cve_id": "CVE-2019-7164",
            "summary": "SQLAlchemy vulnerable to SQL Injection via order_by parameter",
            "description": "SQLAlchemy through 1.2.17 and 1.3.x through 1.3.0b2 allows SQL Injection via the order_by parameter.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-887w-45rq-vxgf",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-7164",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-7164"
                },
                {
                    "url": "https://github.com/sqlalchemy/sqlalchemy/issues/4481"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:0981"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:0984"
                },
                {
                    "url": "https://github.com/advisories/GHSA-887w-45rq-vxgf"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2019/03/msg00020.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujan2021.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00087.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00010.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00016.html"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/11/msg00005.html"
                },
                {
                    "url": "https://github.com/sqlalchemy/sqlalchemy/commit/30307c4616ad67c01ddae2e1e8e34fabf6028414"
                }
            ],
            "published_at": "2019-04-16T15:50:41Z",
            "updated_at": "2023-09-01T09:50:01Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "SQLAlchemy"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 1.3.0",
                    "first_patched_version": {
                        "identifier": "1.3.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-89",
                    "name": "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "SQLAlchemy"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 1.3.0",
            "first_patched_version": {
                "identifier": "1.3.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/13",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/13",
        "created_at": "2024-05-20T13:27:11Z",
        "updated_at": "2024-05-20T13:27:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 12,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "SQLAlchemy"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-38fc-9xqv-7f7q",
            "cve_id": "CVE-2019-7548",
            "summary": "SQLAlchemy is vulnerable to SQL Injection via group_by parameter ",
            "description": "SQLAlchemy 1.2.17 has SQL Injection when the group_by parameter can be controlled.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-38fc-9xqv-7f7q",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-7548",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-7548"
                },
                {
                    "url": "https://github.com/sqlalchemy/sqlalchemy/issues/4481#issuecomment-461204518"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:0981"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:0984"
                },
                {
                    "url": "https://github.com/advisories/GHSA-38fc-9xqv-7f7q"
                },
                {
                    "url": "https://github.com/no-security/sqlalchemy_test"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2019/03/msg00020.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujan2021.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00087.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00010.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00016.html"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/11/msg00005.html"
                }
            ],
            "published_at": "2019-04-16T15:50:39Z",
            "updated_at": "2023-09-01T09:56:01Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "SQLAlchemy"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.3.0",
                    "first_patched_version": {
                        "identifier": "1.3.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-89",
                    "name": "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "SQLAlchemy"
            },
            "severity": "high",
            "vulnerable_version_range": "< 1.3.0",
            "first_patched_version": {
                "identifier": "1.3.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/12",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/12",
        "created_at": "2024-05-20T13:27:11Z",
        "updated_at": "2024-05-20T13:27:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 11,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Jinja2"
            },
            "manifest_path": "etc/requirements_ci.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-462w-v97r-4m45",
            "cve_id": "CVE-2019-10906",
            "summary": "Jinja2 sandbox escape via string formatting",
            "description": "In Pallets Jinja before 2.10.1, `str.format_map` allows a sandbox escape.\n\nThe sandbox is used to restrict what code can be evaluated when rendering untrusted, user-provided templates. Due to the way string formatting works in Python, the `str.format_map` method could be used to escape the sandbox.\n\nThis issue was previously addressed for the `str.format` method in Jinja 2.8.1, which discusses the issue in detail. However, the less-common `str.format_map` method was overlooked. This release applies the same sandboxing to both methods.\n\nIf you cannot upgrade Jinja, you can override the `is_safe_attribute` method on the sandbox and explicitly disallow the `format_map` method on string objects.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-462w-v97r-4m45",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-10906",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-10906"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:1152"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:1237"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:1329"
                },
                {
                    "url": "https://github.com/advisories/GHSA-462w-v97r-4m45"
                },
                {
                    "url": "https://lists.apache.org/thread.html/09fc842ff444cd43d9d4c510756fec625ef8eb1175f14fd21de2605f@%3Cdevnull.infra.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/2b52b9c8b9d6366a4f1b407a8bde6af28d9fc73fdb3b37695fd0d9ac@%3Cdevnull.infra.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/320441dccbd9a545320f5f07306d711d4bbd31ba43dc9eebcfc602df@%3Cdevnull.infra.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/46c055e173b52d599c648a98199972dbd6a89d2b4c4647b0500f2284@%3Cdevnull.infra.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/57673a78c4d5c870d3f21465c7e2946b9f8285c7c57e54c2ae552f02@%3Ccommits.airflow.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/7f39f01392d320dfb48e4901db68daeece62fd60ef20955966739993@%3Ccommits.airflow.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/b2380d147b508bbcb90d2cad443c159e63e12555966ab4f320ee22da@%3Ccommits.airflow.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/f0c4a03418bcfe70c539c5dbaf99c04c98da13bfa1d3266f08564316@%3Ccommits.airflow.apache.org%3E"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DSW3QZMFVVR7YE3UT4YRQA272TYAL5AF/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QCDYIS254EJMBNWOG4S5QY6AOTOR4TZU/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TS7IVZAJBWOHNRDMFJDIZVFCMRP6YIUQ/"
                },
                {
                    "url": "https://palletsprojects.com/blog/jinja-2-10-1-released"
                },
                {
                    "url": "https://usn.ubuntu.com/4011-1/"
                },
                {
                    "url": "https://usn.ubuntu.com/4011-2/"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00030.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00064.html"
                }
            ],
            "published_at": "2019-04-10T14:30:24Z",
            "updated_at": "2023-08-30T21:01:32Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Jinja2"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.10.1",
                    "first_patched_version": {
                        "identifier": "2.10.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N",
                "score": 8.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-693",
                    "name": "Protection Mechanism Failure"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Jinja2"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.10.1",
            "first_patched_version": {
                "identifier": "2.10.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/blaze/dependabot/alerts/11",
        "html_url": "https://github.com/fcas/blaze/security/dependabot/11",
        "created_at": "2024-05-20T13:27:11Z",
        "updated_at": "2024-05-20T13:27:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]