[
    {
        "number": 9,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-fm39-cw8h-3p63",
            "cve_id": "CVE-2019-14491",
            "summary": "Out-of-bounds Read in OpenCV",
            "description": "An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1 (OpenCV-Python before 3.4.7.28 and 4.x before 4.1.1.26). There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-fm39-cw8h-3p63",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-14491",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14491"
                },
                {
                    "url": "https://github.com/opencv/opencv/issues/15125"
                },
                {
                    "url": "https://github.com/opencv/opencv/compare/33b765d...4a7ca5a"
                },
                {
                    "url": "https://github.com/opencv/opencv/compare/371bba8...ddbd10c"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HPFLN6QAX6SUA4XR4NMKKXX26H3TYCVQ/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-fm39-cw8h-3p63"
                }
            ],
            "published_at": "2021-10-12T22:07:14Z",
            "updated_at": "2023-02-01T05:06:27Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 3.4.6.27",
                    "first_patched_version": {
                        "identifier": "3.4.7.28"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 4.0.0.21, <= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 3.4.6.27",
                    "first_patched_version": {
                        "identifier": "3.4.7.28"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 4.0.0.21, <= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 3.4.6.27",
                    "first_patched_version": {
                        "identifier": "3.4.7.28"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 4.0.0.21, <= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 3.4.6.27",
                    "first_patched_version": {
                        "identifier": "3.4.7.28"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 4.0.0.21, <= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:H",
                "score": 8.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 3.4.6.27",
            "first_patched_version": {
                "identifier": "3.4.7.28"
            }
        },
        "url": "https://api.github.com/repos/fcas/deep-high-resolution-net.pytorch/dependabot/alerts/9",
        "html_url": "https://github.com/fcas/deep-high-resolution-net.pytorch/security/dependabot/9",
        "created_at": "2024-05-24T01:33:32Z",
        "updated_at": "2024-05-24T01:33:32Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 8,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-fw99-f933-rgh8",
            "cve_id": "CVE-2019-14492",
            "summary": "Out-of-bounds Read and Out-of-bounds Write in OpenCV",
            "description": "An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1 (OpenCV-Python before 3.4.7.28 and 4.x before 4.1.1.26). There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-fw99-f933-rgh8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-14492",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14492"
                },
                {
                    "url": "https://github.com/opencv/opencv/issues/15124"
                },
                {
                    "url": "https://github.com/opencv/opencv/compare/33b765d...4a7ca5a"
                },
                {
                    "url": "https://github.com/opencv/opencv/compare/371bba8...ddbd10c"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-12/msg00025.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-fw99-f933-rgh8"
                }
            ],
            "published_at": "2021-10-12T22:09:31Z",
            "updated_at": "2023-02-01T05:06:21Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 3.4.6.27",
                    "first_patched_version": {
                        "identifier": "3.4.7.28"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 4.0.0.21, <= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 3.4.6.27",
                    "first_patched_version": {
                        "identifier": "3.4.7.28"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 4.0.0.21, <= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 3.4.6.27",
                    "first_patched_version": {
                        "identifier": "3.4.7.28"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 4.0.0.21, <= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 3.4.6.27",
                    "first_patched_version": {
                        "identifier": "3.4.7.28"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 4.0.0.21, <= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                },
                {
                    "cwe_id": "CWE-787",
                    "name": "Out-of-bounds Write"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 3.4.6.27",
            "first_patched_version": {
                "identifier": "3.4.7.28"
            }
        },
        "url": "https://api.github.com/repos/fcas/deep-high-resolution-net.pytorch/dependabot/alerts/8",
        "html_url": "https://github.com/fcas/deep-high-resolution-net.pytorch/security/dependabot/8",
        "created_at": "2024-05-24T01:33:32Z",
        "updated_at": "2024-05-24T01:33:32Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 7,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-3448-vrgh-85xr",
            "cve_id": "CVE-2019-14493",
            "summary": "NULL Pointer Dereference in OpenCV.",
            "description": "An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-3448-vrgh-85xr",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-14493",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14493"
                },
                {
                    "url": "https://github.com/opencv/opencv/issues/15127"
                },
                {
                    "url": "https://github.com/opencv/opencv/compare/371bba8...ddbd10c"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/10/msg00028.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-3448-vrgh-85xr"
                }
            ],
            "published_at": "2021-10-12T22:21:43Z",
            "updated_at": "2023-02-01T05:06:09Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 4.1.0.25",
            "first_patched_version": {
                "identifier": "4.1.1.26"
            }
        },
        "url": "https://api.github.com/repos/fcas/deep-high-resolution-net.pytorch/dependabot/alerts/7",
        "html_url": "https://github.com/fcas/deep-high-resolution-net.pytorch/security/dependabot/7",
        "created_at": "2024-05-24T01:33:32Z",
        "updated_at": "2024-05-24T01:33:32Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 6,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-hxfw-jm98-v4mq",
            "cve_id": "CVE-2019-15939",
            "summary": "Divide By Zero in OpenCV.",
            "description": "An issue was discovered in OpenCV 4.1.0 (OpenCV-Python 4.1.0.25). There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-hxfw-jm98-v4mq",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-15939",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-15939"
                },
                {
                    "url": "https://github.com/OpenCV/opencv/issues/15287"
                },
                {
                    "url": "https://github.com/opencv/opencv/pull/15382"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-12/msg00025.html"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/10/msg00028.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-hxfw-jm98-v4mq"
                }
            ],
            "published_at": "2021-10-12T22:21:56Z",
            "updated_at": "2023-02-01T05:06:11Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python-headless"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python-headless"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.1.0.25",
                    "first_patched_version": {
                        "identifier": "4.1.1.26"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 5.9
            },
            "cwes": [
                {
                    "cwe_id": "CWE-369",
                    "name": "Divide By Zero"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 4.1.0.25",
            "first_patched_version": {
                "identifier": "4.1.1.26"
            }
        },
        "url": "https://api.github.com/repos/fcas/deep-high-resolution-net.pytorch/dependabot/alerts/6",
        "html_url": "https://github.com/fcas/deep-high-resolution-net.pytorch/security/dependabot/6",
        "created_at": "2024-05-24T01:33:32Z",
        "updated_at": "2024-05-24T01:33:32Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 5,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-x3rm-644h-67m8",
            "cve_id": "CVE-2019-16249",
            "summary": "Out-of-bounds Read in OpenCV",
            "description": "OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-x3rm-644h-67m8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-16249",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-16249"
                },
                {
                    "url": "https://github.com/opencv/opencv/issues/15481"
                },
                {
                    "url": "https://github.com/opencv/opencv/pull/15531"
                },
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1752702"
                },
                {
                    "url": "https://github.com/opencv/opencv-python/releases/tag/30"
                },
                {
                    "url": "https://github.com/advisories/GHSA-x3rm-644h-67m8"
                }
            ],
            "published_at": "2021-10-12T22:22:05Z",
            "updated_at": "2023-02-01T05:06:27Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.1.1.26",
                    "first_patched_version": {
                        "identifier": "4.1.2.30"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python-headless"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.1.1.26",
                    "first_patched_version": {
                        "identifier": "4.1.2.30"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.1.1.26",
                    "first_patched_version": {
                        "identifier": "4.1.2.30"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python-headless"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.1.1.26",
                    "first_patched_version": {
                        "identifier": "4.1.2.30"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 4.1.1.26",
            "first_patched_version": {
                "identifier": "4.1.2.30"
            }
        },
        "url": "https://api.github.com/repos/fcas/deep-high-resolution-net.pytorch/dependabot/alerts/5",
        "html_url": "https://github.com/fcas/deep-high-resolution-net.pytorch/security/dependabot/5",
        "created_at": "2024-05-24T01:33:31Z",
        "updated_at": "2024-05-24T01:33:31Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 4,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-8849-5h85-98qw",
            "cve_id": "CVE-2019-9423",
            "summary": "Out-of-bounds Write in OpenCV",
            "description": "In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation. Product: AndroidVersions: Android-10Android ID: A-110986616",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-8849-5h85-98qw",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-9423",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-9423"
                },
                {
                    "url": "https://source.android.com/security/bulletin/android-10"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2019/10/25/17"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2019/10/27/1"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2019/11/07/1"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2020/12/05/1"
                },
                {
                    "url": "https://github.com/advisories/GHSA-8849-5h85-98qw"
                }
            ],
            "published_at": "2021-10-12T22:22:17Z",
            "updated_at": "2023-02-01T05:06:11Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.1.26",
                    "first_patched_version": null
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.1.26",
                    "first_patched_version": null
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.1.26",
                    "first_patched_version": null
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.1.26",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "score": 7.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-787",
                    "name": "Out-of-bounds Write"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 4.1.1.26",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/fcas/deep-high-resolution-net.pytorch/dependabot/alerts/4",
        "html_url": "https://github.com/fcas/deep-high-resolution-net.pytorch/security/dependabot/4",
        "created_at": "2024-05-24T01:33:31Z",
        "updated_at": "2024-05-24T01:33:31Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 3,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jggw-2q6g-c3m6",
            "cve_id": "CVE-2019-19624",
            "summary": "Out-of-bounds Read in OpenCV",
            "description": "An out-of-bounds read was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.0.25). Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-jggw-2q6g-c3m6",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-19624",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-19624"
                },
                {
                    "url": "https://github.com/opencv/opencv/issues/14554"
                },
                {
                    "url": "https://github.com/opencv/opencv/commit/d1615ba11a93062b1429fce9f0f638d1572d3418"
                },
                {
                    "url": "https://access.redhat.com/security/cve/cve-2019-19624"
                },
                {
                    "url": "https://github.com/opencv/opencv-python/releases/tag/25"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jggw-2q6g-c3m6"
                }
            ],
            "published_at": "2021-10-12T22:22:58Z",
            "updated_at": "2023-02-01T05:06:08Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.1.0.24",
                    "first_patched_version": {
                        "identifier": "4.1.0.25"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python-headless"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.1.0.24",
                    "first_patched_version": {
                        "identifier": "4.1.0.25"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.1.0.24",
                    "first_patched_version": {
                        "identifier": "4.1.0.25"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python-headless"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 4.1.0.24",
                    "first_patched_version": {
                        "identifier": "4.1.0.25"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L",
                "score": 6.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 4.1.0.24",
            "first_patched_version": {
                "identifier": "4.1.0.25"
            }
        },
        "url": "https://api.github.com/repos/fcas/deep-high-resolution-net.pytorch/dependabot/alerts/3",
        "html_url": "https://github.com/fcas/deep-high-resolution-net.pytorch/security/dependabot/3",
        "created_at": "2024-05-24T01:33:31Z",
        "updated_at": "2024-05-24T01:33:31Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 2,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-m6vm-8g8v-xfjh",
            "cve_id": "CVE-2019-5063",
            "summary": "Out-of-bounds Write in OpenCV",
            "description": "An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0 (corresponds with OpenCV-Python 4.1.0.25). A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-m6vm-8g8v-xfjh",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-5063",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-5063"
                },
                {
                    "url": "https://github.com/opencv/opencv/issues/16951"
                },
                {
                    "url": "https://github.com/opencv/opencv-python/releases/tag/25"
                },
                {
                    "url": "https://talosintelligence.com/vulnerability_reports/TALOS-2019-0852"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpuApr2021.html"
                },
                {
                    "url": "https://www.oracle.com//security-alerts/cpujul2021.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-m6vm-8g8v-xfjh"
                }
            ],
            "published_at": "2021-10-12T22:23:13Z",
            "updated_at": "2023-02-01T05:06:08Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.0.25",
                    "first_patched_version": null
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.0.25",
                    "first_patched_version": null
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.0.25",
                    "first_patched_version": null
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.0.25",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-787",
                    "name": "Out-of-bounds Write"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 4.1.0.25",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/fcas/deep-high-resolution-net.pytorch/dependabot/alerts/2",
        "html_url": "https://github.com/fcas/deep-high-resolution-net.pytorch/security/dependabot/2",
        "created_at": "2024-05-24T01:33:31Z",
        "updated_at": "2024-05-24T01:33:31Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 1,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-q799-q27x-vp7w",
            "cve_id": "CVE-2019-5064",
            "summary": "Out-of-bounds Write in OpenCV",
            "description": "An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, version 4.1.0 (corresponds with OpenCV-Python version 4.1.2.30). A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-q799-q27x-vp7w",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-5064",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-5064"
                },
                {
                    "url": "https://github.com/opencv/opencv/issues/15857"
                },
                {
                    "url": "https://github.com/opencv/opencv-python/releases/tag/32"
                },
                {
                    "url": "https://github.com/opencv/opencv/releases/tag/4.2.0"
                },
                {
                    "url": "https://talosintelligence.com/vulnerability_reports/TALOS-2019-0853"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpuApr2021.html"
                },
                {
                    "url": "https://www.oracle.com//security-alerts/cpujul2021.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-q799-q27x-vp7w"
                }
            ],
            "published_at": "2021-10-12T22:23:21Z",
            "updated_at": "2023-04-21T15:01:19Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.2.30",
                    "first_patched_version": {
                        "identifier": "4.2.0.32"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.2.30",
                    "first_patched_version": {
                        "identifier": "4.2.0.32"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.2.30",
                    "first_patched_version": {
                        "identifier": "4.2.0.32"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "opencv-contrib-python-headless"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 4.1.2.30",
                    "first_patched_version": {
                        "identifier": "4.2.0.32"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                },
                {
                    "cwe_id": "CWE-787",
                    "name": "Out-of-bounds Write"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "opencv-python"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 4.1.2.30",
            "first_patched_version": {
                "identifier": "4.2.0.32"
            }
        },
        "url": "https://api.github.com/repos/fcas/deep-high-resolution-net.pytorch/dependabot/alerts/1",
        "html_url": "https://github.com/fcas/deep-high-resolution-net.pytorch/security/dependabot/1",
        "created_at": "2024-05-24T01:33:31Z",
        "updated_at": "2024-05-24T01:33:31Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]